{% set version = "0.91" %}
{% set sha256 = "3d428440f7a8aed3be18bbe094d3afe94f2d5357daa715d13e963c665384f2ab" %}
{% set name = "phylogenize" %}

package:
  name: phylogenize
  version: "{{ version }}"

source: 
  git_url: https://github.com/pbradleylab/phylogenize.git
  git_tag: v{{ version }}

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - perl
    - r-base>=4.1,<4.2.0a0
    - vsearch
    - r-ragg
    - r-phangorn
    - r-pbapply
    - r-phylolm
    - r-tidyverse
    - r-pryr
    - r-svglite
    - r-functional
    - r-settings
    - r-gtools
    - r-furrr
    - r-phytools
    - r-kableExtra
    - r-testthat
    - r-seqinr
    - 'bioconductor-ggtree'
    - 'bioconductor-biomformat'
    - 'bioconductor-qvalue'
  run:
    - perl
    - r-base>=4.1,<4.2.0a0
    - vsearch
    - r-ragg
    - r-phangorn
    - r-pbapply
    - r-phylolm
    - r-tidyverse
    - r-pryr
    - r-svglite
    - r-functional
    - r-settings
    - r-gtools
    - r-furrr
    - r-phytools
    - r-kableExtra
    - r-testthat
    - r-seqinr
    - 'bioconductor-ggtree'
    - 'bioconductor-biomformat'
    - 'bioconductor-qvalue'

test:
  commands:
    - '$R -e "library(phylogenize)"'

about:
  home: https://github.com/pbradleylab/phylogenize
  license: MIT
  summary: "Phylogenize is a tool that allows users to link microbial genes to environments, accounting for phylogeny."
extra:
  recipe-maintainers:
    - kekananen
  indentifiers:
    - doi: "https://doi.org/10.1093/bioinformatics/btz722"
