{% set name = "phylogenize" %}
{% set version = "2.0.0" %}
{% set sha256 = "328a03c661e908ff49b55f98eeaa29540edf83193995ff698db9456a09f42220" %}

package:
  name: phylogenize
  version: {{ version }}

source:
  url: https://github.com/pbradleylab/{{ name }}/archive/refs/tags/v2.0.0.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin = "x.x") }}

requirements:
  host:
    - r-base >=4.2
    - vsearch =2.30.0
    - repermulize =1.0.0
    - conda-forge::r-stringi >=1.8.0
    - conda-forge::icu >=73.2
    - r-stringr
    - r-tidyverse
    - r-ragg
    - r-phangorn
    - r-pryr
    - r-svglite
    - r-functional
    - r-settings
    - r-gtools
    - r-furrr
    - r-scales
    - r-phytools
    - r-testthat
    - r-ggiraph
    - r-tidymodels
    - r-extradistr
    - bioconductor-ancombc
    - bioconductor-maaslin2
    - bioconductor-clusterprofiler
  run:
    - r-base >=4.2,<4.3.0a0
    - vsearch =2.30.0
    - repermulize =1.0.0
    - conda-forge::r-stringi >=1.8.0
    - conda-forge::icu >=70
    - r-stringr
    - r-tidyverse
    - r-ragg
    - r-phangorn
    - r-pryr
    - r-svglite
    - r-functional
    - r-settings
    - r-gtools
    - r-furrr
    - r-scales
    - r-phytools
    - r-testthat
    - r-ggiraph
    - r-tidymodels
    - r-extradistr
    - bioconductor-ancombc
    - bioconductor-maaslin2
    - bioconductor-clusterprofiler

test:
  commands:
    - '$R -e "library(phylogenize)"'

about:
  home: "https://github.com/pbradleylab/phylogenize"
  dev_url: "https://github.com/pbradleylab/phylogenize"
  license: MIT
  license_family: MIT
  summary: "Phylogenize is a tool that allows users to link microbial genes to environments, accounting for phylogeny."
  doc_url: "http://phylogenize.org"

extra:
  recipe-maintainers:
    - kekananen
  indentifiers:
    - doi:10.1093/bioinformatics/btz722
