{% set version = "0.91" %}
{% set sha256 = "3d428440f7a8aed3be18bbe094d3afe94f2d5357daa715d13e963c665384f2ab" %}
{% set name = "phylogenize" %}

package:
  name: phylogenize
  version: "{{ version }}"

source: 
  url: https://github.com/pbradleylab/phylogenize/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - perl
    - r-base
    - r-devtools
    - vsearch
    - r-ragg
    - r-phylom
    - r-phangorn
    - 'bioconductor-ggtree'
    - 'bioconductor-biomformat'
  run:
    - perl
    - vsearch
    - r-base
    - 'bioconductor-ggtree'
    - 'bioconductor-biomformat'
    - r-devtools
    - r-ragg
    - r-phylolm
    - r-phangorn

test:
  commands:
    - '$R -e "library(devtools)"'
    - $R -e "devtools::install_github('pbradleylab/phylogenize/package/phylogenize')"
    - '$R -e "?phylogenize"'

about:
  home: https://github.com/pbradleylab/phylogenize
  license: MIT
  summary: "Phylogenize is a tool that allows users to link microbial genes to environments, accounting for phylogeny."
extra:
  recipe-maintainers:
    - kathryn kananen
  indentifiers:
    - doi: "https://doi.org/10.1093/bioinformatics/btz722"
