{% set version = "0.91" %}
{% set name = "phylogenize" %}

package:
  name: phylogenize
  version: "{{ version }}"

source: 
  url: https://github.com/pbradleylab/phylogenize/archive/refs/tags/v{{ version }}.tar.gz
  build:
    name: 0
    rpaths:
      - lib/R/lib/
      - lib/
    noarch: generic

requirements:
  build:
    - vsearch
    - bioconductor-ggtree
    - bioconductor-biomformat
    - r-devtools
    - r-ragg
    - r-phylolm
    - r-phangorn
  run:
    - vsearch
    - bioconductor-ggtree
    - bioconductor-biomformat
    - r-devtools
    - r-ragg
    - r-phylolm
    - r-phangorn
  test:
    commands:
      - '$R -c "library(''{{ name }}'')"'

about:
  home: https://github.com/bitbucket/phylogenize
  license: MIT
  summary: "An R package that allows users to link microbial genes to environments, accounting for phylogeny"
  summary: "Phylogenize is a tool that allows users to link microbial genes to environments, accounting for phylogeny. More specifically, given community composition data, Phylogenize links genes in microbial genomes to either microbial prevalence in, or specificity for, a given environment, while also taking into account an important potential confounder: the phylogenetic relationships between microbes."
  extra:
    recipe-maintainers:
      - kathrynkananen
    indentifiers:
      - doi: https://doi.org/10.1093/bioinformatics/btz722
