{% set name = "phylogenize" %}
{% set version = "2.0.0" %}
{% set sha256 = "328a03c661e908ff49b55f98eeaa29540edf83193995ff698db9456a09f42220" %}

package:
  name: phylogenize
  version: {{ version }}

source:
  url: https://github.com/pbradleylab/{{ name }}/archive/refs/tags/v2.0.0.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin = "x.x") }}

requirements:
  host:
    - r-base >=4.2
    - vsearch =2.30.0
    - repermulize =1.0.0
    - conda-forge::r-stringi >=1.8.0
    - conda-forge::icu >=70
    - r-stringr =1.5.0 
    - r-tidyverse =1.3.1
    - r-ragg =1.2.2
    - r-phangorn =2.8.1
    - r-pryr =0.1.5
    - r-svglite =2.1.0
    - r-functional =0.6
    - r-settings =0.2.7
    - r-gtools =3.9.2.1
    - r-furrr =0.3.0
    - r-scales =1.3.0
    - r-phytools =2.3_0
    - r-testthat =3.1.4
    - r-ggiraph =0.8.10
    - r-tidymodels =1.2.0
    - r-extradistr =1.9.1
    - bioconductor-ancombc =2.0.1
    - bioconductor-maaslin2 =1.12.0
    - bioconductor-clusterprofiler =4.6.0
  run:
    - r-base >=4.2,<4.3.0a0
    - vsearch =2.30.0
    - repermulize =1.0.0
    - conda-forge::r-stringi >=1.8.0
    - conda-forge::icu >=70
    - r-stringr =1.5.0
    - r-tidyverse =1.3.1
    - r-ragg =1.2.2
    - r-phangorn =2.8.1
    - r-pryr =0.1.5
    - r-svglite =2.1.0
    - r-functional =0.6
    - r-settings =0.2.7
    - r-gtools =3.9.2.1
    - r-furrr =0.3.0
    - r-scales =1.3.0
    - r-phytools =2.3_0
    - r-testthat =3.1.4
    - r-ggiraph =0.8.10
    - r-tidymodels =1.2.0
    - r-extradistr =1.9.1
    - bioconductor-ancombc =2.0.1
    - bioconductor-maaslin2 =1.12.0
    - bioconductor-clusterprofiler =4.6.0

test:
  commands:
    - '$R -e "library(phylogenize)"'

about:
  home: "https://github.com/pbradleylab/phylogenize"
  dev_url: "https://github.com/pbradleylab/phylogenize"
  license: MIT
  license_family: MIT
  summary: "Phylogenize is a tool that allows users to link microbial genes to environments, accounting for phylogeny."
  doc_url: "http://phylogenize.org"

extra:
  recipe-maintainers:
    - kekananen
  indentifiers:
    - doi:10.1093/bioinformatics/btz722
